# Fly.io configuration for RAG Application Backend
app = "rag-app-9pwbjw"
primary_region = "dfw"

[build]

[env]
  APP_ENV = "production"
  PORT = "8000"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "10s"
  tls_skip_verify = false

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1