# Render Blueprint for RAG Application
# This file defines the infrastructure as code for Render deployment

services:
  - type: web
    name: rag-api
    runtime: python3
    plan: free  # Start with free tier
    branch: main
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: APP_ENV
        value: production
      - key: PORT
        generateValue: true
    
    # Auto-deploy on git push
    autoDeploy: true
    
    # Custom domains (add after deployment)
    # customDomains:
    #   - name: api.yourdomain.com