name: Deploy Backend to Fly.io

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Set Groq API Key (if available)
        run: |
          if [ -n "${{ secrets.GROQ_API_KEY }}" ]; then
            flyctl secrets set GROQ_API_KEY="${{ secrets.GROQ_API_KEY }}" -a rag-app-9pwbjw --access-token ${{ secrets.FLY_API_TOKEN }}
          fi
          
      - name: Deploy to Fly.io
        run: |
          cd backend
          flyctl deploy --remote-only --access-token ${{ secrets.FLY_API_TOKEN }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}